version: 2.0
jobs:
  build:
    docker:
      - image: cimg/ruby:3.0-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "Hello World"